# Generated by Django 3.0.5 on 2020-09-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('demand', models.CharField(max_length=128)),
                ('distance', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('pub_year', models.CharField(max_length=32)),
                ('pub_month', models.CharField(max_length=32)),
                ('pub_day', models.CharField(max_length=32)),
            ],
        ),
    ]
